source 'https://github.com/CocoaPods/Specs.git'


target 'ResplendentUtilities', :exclusive => true do
  pod "ResplendentUtilities", :path => "../"

  pod 'Specta', '1.0.4'
  pod 'Expecta', '1.0.3'
end
