platform :ios, '7.0'
use_frameworks!

def sharedPods
  pod 'ResplendentUtilities', :path => '../'
end

target 'ResplendentUtilities_Example' do
  sharedPods
end

target 'ResplendentUtilities_Tests' do
  sharedPods

  pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
end
